[package]
name = "rc5_test"
version = "0.1.0"
authors = ["Ben Marsh <ben.marsh@mintlayer.org>"]
edition = "2018"

[dependencies]
num-traits = "0.2.15"
zeroize = { version = "1.5.3", features = ["derive"] }
